export const surpriseMePrompts = [
    "A city skyline at night with a full moon in the background",
    "A dragon breathing fire in a forest ",
    " A mermaid sitting on a rock in the middle of the ocean",
    "A person standing on top of a cliff overlooking the ocean at sunset ",
    "A majestic eagle soaring through a clear blue sky with snow-capped mountains in the background, its wings spread wide and its eyes fixed on its prey",
    "A magical underwater world filled with colorful coral reefs, schools of tropical fish, and a giant octopus guarding a hidden treasure ",
    " A futuristic cityscape with towering skyscrapers, flying cars, and neon lights illuminating the night sky, as a group of rebels fight against a tyrannical government",
    " A mystical forest with ancient trees, glowing mushrooms, and a hidden portal that leads to a magical realm",
    " A post-apocalyptic wasteland with ruins of a once-great civilization, where a lone survivor searches for a way to rebuild and restore hope",
    " A grand ballroom filled with elegant dancers in elaborate costumes, as a masked figure plots a sinister scheme in the shadows",
    " A serene countryside with rolling hills, a babbling brook, and a cozy cottage nestled among the trees, where a wise old hermit imparts his knowledge to a young apprentice",
    "panda mad scientist mixing sparkling chemicals, digital art",
    "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
    "an astronaut lounging in a tropical resort in space, vaporwave",
    "A BBQ that is alive, in the style of a Pixar animated movie",
    "A giant tree with a treehouse in the branches ",
    " A phoenix rising from the ashes",
    "A photo of a white fur monster standing in a purple room",
    "A realistic photograph of a young woman with blue eyes and blonde hair",
    "A man standing in front of a stargate to another dimension",
    "a bowl of soup that looks like a monster, knitted out of wool",
    " A person walking through a city street in the rain",
    " A person standing in front of a giant castle",
    "A person standing in a field of wheat with a windmill in the background ",
    " A person standing on a hill with a wind turbine in the background",
    " A bustling marketplace in a far-off land, where exotic spices, rare artifacts, and mystical potions are sold by merchants from all over the world",
    "A person walking through a desert with a camel ",
    " A person standing in front of a giant glacier",
    "A synthwave style sunset above the reflecting water of the sea, digital art",
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    "Two futuristic towers with a skybridge covered in lush foliage, digital art",
    "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
    "A comic book cover of a superhero wearing headphones",
    "A centered explosion of colorful powder on a black background",
    "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
    "A futuristic cyborg dance club, neon lights",
    "A haunted castle on a hill, where a ghostly apparition roams the halls and a cursed treasure lies hidden in the depths of the dungeon ",
    " A castle on top of a mountain with a waterfall in the background",
    " A magical forest with glowing mushrooms and fireflies",
    " A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
    "an armchair in the shape of an avocado",
    "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
    "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
    "The long-lost Star Wars 1990 Japanese Anime",
    "A hamburger in the shape of a Rubik’s cube, professional food photography",
    "A Synthwave Hedgehog, Blade Runner Cyberpunk",
    "A space station orbiting a distant planet, where a team of astronauts must battle against an alien invasion to save humanity ",
    "An astronaut encountering an alien life form on a distant planet, photography",
    "A photograph of a cyborg exploring Tokyo at night, lomography",
    "Synthwave aeroplane",
    "A Space Shuttle flying above Cape Town, digital art",
    "A velociraptor working at a hotdog stand, lomography",
    "Spongebob Squarepants in the Blair Witch Project",
    "a stained glass window depicting a hamburger and french fries",
    "a pencil and watercolor drawing of a bright city in the future with flying cars",
    " A person riding a bicycle through a rainbow",
    "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    "a painting of a fox in the style of Starry Night",
];
